services:
    homeassistant:
        container_name: homeassistant
        privileged: true
        restart: unless-stopped
        environment:
            - TZ=${TZ}
        volumes:
            - ./data:/config
            - /run/dbus:/run/dbus:ro
        network_mode: host
        image: ghcr.io/home-assistant/home-assistant:stable
