services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
    networks:
      - private

  redis:
    image: redis:alpine
    restart: always
    networks:
      - private

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    depends_on:
      - db
      - redis
    ports:
    - "${NEXTCLOUD_PORT}:80"
    volumes:
      - ./data:/var/www/html/data
      - ./config:/var/www/html/config
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}
      - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}

      - OVERWRITEPROTOCOL=https
      - OVERWRITECLIURL=${NEXTCLOUD_DOMAIN}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
    networks:
      - private

networks:
  private: