name: boom-mc

services:
  crafty:
    container_name: crafty
    image: registry.gitlab.com/crafty-controller/crafty-4:4.10.4
    restart: always
    environment:
      - TZ=${TZ}
    ports:
      - "${CRAFTY_WEB_UI_PORT}:8443"        # HTTPS Web UI
    volumes:
      - ./crafty-data/backups:/crafty/backups
      - ./crafty-data/logs:/crafty/logs
      - ./crafty-data/servers:/crafty/servers
      - ./crafty-data/config:/crafty/app/config
      - ./crafty-data/import:/crafty/import
    networks:
      mcnet:
        ipv4_address: 172.31.50.4
    depends_on:
      mysql:
        condition: service_started

  mysql:
    container_name: luckperms-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${LUCKPERMS_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${LUCKPERMS_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${LUCKPERMS_MYSQL_USER}
      MYSQL_PASSWORD: ${LUCKPERMS_MYSQL_PASSWORD}
    hostname: luckperms-db
    volumes:
      - ./luckperms-db:/var/lib/mysql
    networks:
      mcnet:

  playit:
    image: ghcr.io/playit-cloud/playit-agent:latest
    container_name: playit-agent
    restart: always
    environment:
      - SECRET_KEY=${PLAYIT_KEY}
    networks:
      mcnet:

networks:
  mcnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.50.0/24

